apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-kpi-config
  labels:
    app.kubernetes.io/name: ms-kpi
    app.kubernetes.io/part-of: innovatech
    app.kubernetes.io/component: microservice
data:
  PORT: "3004"
  NODE_ENV: "production"
  API_GATEWAY_PREFIX: "/api/v1"
  PROJECT_MANAGER_BASE_URL: "http://ms-project-manager:3002"
  PROJECT_MANAGER_API_PREFIX: "/api/v1"
