apiVersion: v1
kind: Service
metadata:
  name: kpi
  labels:
    app.kubernetes.io/name: ms-kpi
    app.kubernetes.io/part-of: innovatech
    app.kubernetes.io/component: microservice
spec:
  type: ClusterIP
  selector:
    app: kpi
  ports:
    - name: http
      port: 3004
      targetPort: http
      protocol: TCP
