apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: innovatech

resources:
  - namespace.yaml
  - postgres
  - ingress.yaml
  - ../ms-users/k8s
  - ../ms-auth/k8s
  - ../ms-project-manager/k8s
  - ../ms-kpi/k8s
  - ../bff/k8s
  - ../api-gateway/k8s
  - ../../frontend/k8s
