apiVersion: v1
kind: Service
metadata:
  name: ms-users
  labels:
    app.kubernetes.io/name: ms-users
    app.kubernetes.io/part-of: innovatech
    app.kubernetes.io/component: microservice
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ms-users
  ports:
    - name: http
      port: 3003
      targetPort: http
      protocol: TCP
