global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ms-auth
    static_configs:
      - targets: ['auth:3001']
    metrics_path: /api/metrics

  - job_name: ms-users
    static_configs:
      - targets: ['users:3003']
    metrics_path: /metrics

  - job_name: ms-project-manager
    static_configs:
      - targets: ['project-manager:3002']
    metrics_path: /metrics
