apiVersion: v1
kind: Service
metadata:
  name: bff
  labels:
    app.kubernetes.io/name: bff
    app.kubernetes.io/part-of: innovatech
    app.kubernetes.io/component: bff
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bff
  ports:
    - name: http
      port: 3010
      targetPort: http
      protocol: TCP
