apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-auth-config
  labels:
    app.kubernetes.io/name: ms-auth
    app.kubernetes.io/part-of: innovatech
    app.kubernetes.io/component: microservice
data:
  PORT: "3001"
  NODE_ENV: "production"
  JWT_EXPIRES_IN: "1h"
  JWT_ISSUER: "innovatech-auth"
  USERS_SERVICE_URL: "http://ms-users:3003"
