apiVersion: v1
kind: Service
metadata:
  name: ms-auth
  labels:
    app.kubernetes.io/name: ms-auth
    app.kubernetes.io/part-of: innovatech
    app.kubernetes.io/component: microservice
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ms-auth
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
