apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-project-manager-config
  labels:
    app.kubernetes.io/name: ms-project-manager
    app.kubernetes.io/part-of: innovatech
    app.kubernetes.io/component: microservice
data:
  PORT: "3002"
  NODE_ENV: "production"
  API_GATEWAY_PREFIX: "/api/v1"
